### ISSUE TITLE
RES- Tab System Tablet and Mobile layouts

### ISSUE THREAD

**Issue by SingenSmythe** [SingenSmythe/excise#66]
The Tab system works fine for the web layout as it incorporates mouse scroll but on Tablet and Mobile this will change to touch. A better alternative to the tab system on these resolutions would be to have the titles from the left side of the tabs to appear as links that expand when touched to reveal the relevant panel rather than having to scroll downwards to see the existing panel?

**Comment by davekls** [comment]
Sounds good but I'd probably need to see a version of this before I can make a decision.
